spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/appcenterstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jwt:
    secretKey : inuappcenter

logging.level:
  org.hibernate.SQL: debug
